# Basic
title: KuoYu's blog
subtitle: a poor student
welcome_message: welcome come to my site
creator: <a href="#">KuoYu</a>

url: "kuoyu2tap.me"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: Projects, description: My Projects, url: 'https://github.com/KuoYu2tap'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    weibo: None
    github: KuoYu2tap
    twitter: None
    mail: kuoyu2tap@gmail.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
